<style  type="text/css"> 
cool {
  width: 100px;
  height: 100px;
  background-color: red;
  position: relative;
  -webkit-animation-name: example; /* Safari 4.0 - 8.0 */
  -webkit-animation-duration: 4s; /* Safari 4.0 - 8.0 */
  -webkit-animation-iteration-count: infinite; /* Safari 4.0 - 8.0 */
  animation-name: example;
  animation-duration: 4s;
  animation-iteration-count: infinite;
}

/* Safari 4.0 - 8.0 */
@-webkit-keyframes example {
  0%   {background-color:red; left:0px; top:0px;}
  25%  {background-color:yellow; left:200px; top:0px;}
  50%  {background-color:blue; left:200px; top:200px;}
  75%  {background-color:green; left:0px; top:200px;}
  100% {background-color:red; left:0px; top:0px;}
}

/* Standard syntax */
@keyframes example {
  0%   {background-color:red; left:0px; top:0px;}
  25%  {background-color:yellow; left:200px; top:0px;}
  50%  {background-color:blue; left:200px; top:200px;}
  75%  {background-color:green; left:0px; top:200px;}
  100% {background-color:red; left:0px; top:0px;}
}
</style>

<b><center>
<span style="font-size: 24pt; line-height: 1.2">
COMS W4111: Introduction to Databases<br>
Spring 2020, Sections 002, H02, V02
</span>
</center></b>
</span><br>
<p>
<i><center>
<span style="font-size: 20pt; line-height: 1.2">
Non-Programming Project Notebook<br>
</span>
</center></i>

# Introduction

- This notebook defines HW1, Part C for both the programming and no-programming tracks.


- Submission instructions:
    - Both no programming and programming tracks submit a zip file containing all of the files in the HW project directory that you clone (see below).
    - Much of your work is completing sections of this notebook, but you MUST edit the copy in the project directory.
    - If you reference or create any files, please create in the project directory.
    - The name of your zip file MUST be ```uni_W4111_s20_hw1c,```  replace ```uni``` with you UNI. My submission would be ```dff9_W4111_s20_hw1c.```
    - The homework is due on 23-February-2020 at 11:59 PM. You MAY use late days.
    
- We will use the pinned [Piazza post](https://piazza.com/class/k5grpo7gmn71pj?cid=301) to clarify the homework and answer questions.


# Common Setup

Both tracks should:
- MySQL: Install
    - [MySQL Server Community Edition](https://dev.mysql.com/doc/mysql-installation-excerpt/8.0/en/)
    - [MySQL Workbench](https://dev.mysql.com/doc/workbench/en/)
    - In addition to the official links, there are many operating specific tutorials.
    
    
- Create a [Lucidchart educational account.](https://lucidchart.zendesk.com/hc/en-us/articles/207324096-Get-Started-with-an-Educational-Account)


- Project template:
    - If you do not have ```Git``` on your computer, please install it.
    - Homework 1 setup instructions recommended that you create a folder ```/IntroToDB``` on your desktop.
    - Under this directory, create a folder ```HW1C.```
    - Open terminal shell or Git enabled command prompt.
    - CD to the directory you created and enter ```git clone https://github.com/donald-f-ferguson/GoTHW```
    - This will create the project template for you.
        
| <img src="./got_hw_project.png"> |
| :---: |
| __HW1C Project Template__ |

- Run the following cells. Your answers WILL BE different than the sample output.

In [50]:
import sys
import os
import platform
import psutil

print("="*40, "Path Information", "="*40)
print("Path = ", os.getcwd())

print("="*40, "System Information", "="*40)
uname = platform.uname()
print(f"System: {uname.system}")
print(f"Node Name: {uname.node}")
print(f"Release: {uname.release}")
print(f"Version: {uname.version}")
print(f"Machine: {uname.machine}")
print(f"Processor: {uname.processor}")

print("="*40, "Network Information", "="*40)

import socket    
hostname = socket.gethostname()    
IPAddr = socket.gethostbyname(hostname)    
print("Your Computer Name is:" + hostname)    
print("Your Computer IP Address is:" + IPAddr) 

import uuid
print ("Your MAC address is:", hex(uuid.getnode()))

======================================== Path Information ========================================
Path =  /Users/zjh/Desktop/Columbia/term 2/Intro to database/HW1C/GoTHW
======================================== System Information ========================================
System: Darwin
Node Name: dyn-129-236-220-50.dyn.columbia.edu
Release: 19.2.0
Version: Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64
Machine: x86_64
Processor: i386
======================================== Network Information ========================================
Your Computer Name is:dyn-129-236-220-50.dyn.columbia.edu
Your Computer IP Address is:129.236.220.50
Your MAC address is: 0xacde48001122

# No Programming

## Overview

The no-programming track has four tasks:

1. Import CSV data files and create initial tables.<br><br>
2. Create a new schema by modifying and improving the data schema and content.<br><br>
3. Defining a set of views that support data visualizations.<br><br>
4. Running Python cells that produce visualization using the provided code.

## Task 1: Initial Data Import

### Task

- The folder in the project ```Data/csv``` contains several CSV files:
    - ```'character_relationships.csv```
    - ```characters.csv```
    - ```characters_actors.csv```
    - ```episodes.csv```
    - ```locations.csv```
    - ```scenes.csv```
    - ```scenes_characters.csv```
    
    
- Use MySQL Workbench:
    - Create a new schema ```W4111GoTSolution``` and set as the default schema.
    - Use the MySQL [Workbench Table Data Import Wizard](https://dev.mysql.com/doc/workbench/en/wb-admin-export-import-table.html) and import each of the files. Choose the option to create a new table.

### Tests

In [51]:
%load_ext sql
%sql mysql+pymysql://root:Tiao2680230@localhost/W4111GoTSolution

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

'Connected: root@W4111GoTSolution'

```1.``` Find all the characters with last name ```Stark.```

In [35]:
%sql select * from characters where characterName like("% Stark")

 * mysql+pymysql://root:***@localhost/W4111GoTSolution
14 rows affected.

[(15, 'Arya Stark', '/character/ch0158604/', 'Maisie Williams', '/name/nm3586035/', 'CH_15', None, 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTk5MTYwNDc0OF5BMl5BanBnXkFtZTcwOTg2NDg1Nw@@._V1._SX100_SY140_.jpg', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTk5MTYwNDc0OF5BMl5BanBnXkFtZTcwOTg2NDg1Nw@@._V1_SY1000_CR0,0,665,1000_AL_.jpg', None, None),
 (20, 'Benjen Stark', '/character/ch0153996/', 'Joseph Mawle', '/name/nm1152798/', 'CH_20', None, 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjFiY2M5MjgtZmRiMS00ZTAyLTk2Y2UtMjdjZTRkZmVlYTMyXkEyXkFqcGdeQXVyMjk3NTUyOTc@._V1._SX100_SY140_.jpg', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjFiY2M5MjgtZmRiMS00ZTAyLTk2Y2UtMjdjZTRkZmVlYTMyXkEyXkFqcGdeQXVyMjk3NTUyOTc@._V1_.jpg', None, None),
 (28, 'Brandon Stark', None, None, None, 'CH_28', None, None, None, None, None),
 (29, 'Bran Stark', '/character/ch0234897/', 'Isaac Hempstead Wright', '/name/nm3652842/', 'CH_29', 1, 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTA1NTg0NTI3MTBeQTJeQWpwZ15BbWU3MDEyNjg4OTQ@._V1._SX100_SY140_.jpg', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTA1NTg0NTI3MTBeQTJeQWpwZ15BbWU3MDEyNjg4OTQ@._V1_SX1500_CR0,0,1500,999_AL_.jpg', None, None),
 (36, 'Catelyn Stark', '/character/ch0145135/', 'Michelle Fairley', '/name/nm0265610/', 'CH_36', None, 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTY2ODc4MTkxMV5BMl5BanBnXkFtZTcwNjM3MTg4OQ@@._V1._SX100_SY140_.jpg', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTY2ODc4MTkxMV5BMl5BanBnXkFtZTcwNjM3MTg4OQ@@._V1_SY1000_CR0,0,915,1000_AL_.jpg', None, None),
 (59, 'Eddard Stark', '/character/ch0154681/', 'Sean Bean', '/name/nm0000293/', 'CH_59', None, 'https://images-na.ssl-images-amazon.com/images/M/MV5BODcwMjg0MDQ5MF5BMl5BanBnXkFtZTcwMTk2NDk4OQ@@._V1._SX100_SY140_.jpg', 'https://images-na.ssl-images-amazon.com/images/M/MV5BODcwMjg0MDQ5MF5BMl5BanBnXkFtZTcwMTk2NDk4OQ@@._V1_SY1000_CR0,0,827,1000_AL_.jpg', 'Ned', None),
 (183, 'Lyanna Stark', '/character/ch0543804/', 'Aisling Franciosi', '/name/nm4957233/', 'CH_183', None, 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTE5NTczY2QtNmQxYS00NTAwLWE2ZTAtYzc1MTkyZGU5MzRkL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMjk3NTUyOTc@._V1._SX100_SY140_.jpg', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTE5NTczY2QtNmQxYS00NTAwLWE2ZTAtYzc1MTkyZGU5MzRkL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMjk3NTUyOTc@._V1_.jpg', None, None),
 (284, 'Rickard Stark', None, None, None, 'CH_284', None, None, None, None, None),
 (285, 'Rickon Stark', '/character/ch0233141/', 'Art Parkinson', '/name/nm3280686/', 'CH_285', None, 'https://images-na.ssl-images-amazon.com/images/M/MV5BMWZiOGNjMDAtOTRlNi00MDJmLWEyMTMtOGEwZTM5ODJlNDAyXkEyXkFqcGdeQXVyMjk3NTUyOTc@._V1._SX100_SY140_.jpg', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMWZiOGNjMDAtOTRlNi00MDJmLWEyMTMtOGEwZTM5ODJlNDAyXkEyXkFqcGdeQXVyMjk3NTUyOTc@._V1_.jpg', None, None),
 (286, 'Robb Stark', '/character/ch0158596/', 'Richard Madden', '/name/nm0534635/', 'CH_286', 1, 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjI2NDE1NzczNF5BMl5BanBnXkFtZTcwNjcwODg4OQ@@._V1._SX100_SY140_.jpg', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjI2NDE1NzczNF5BMl5BanBnXkFtZTcwNjcwODg4OQ@@._V1_SY1000_CR0,0,845,1000_AL_.jpg', None, None),
 (300, 'Sansa Stark', '/character/ch0158137/', 'Sophie Turner', '/name/nm3849842/', 'CH_300', 1, 'https://images-na.ssl-images-amazon.com/images/M/MV5BNjAwMjE2NDExNF5BMl5BanBnXkFtZTcwODAwODg4OQ@@._V1._SX100_SY140_.jpg', 'https://images-na.ssl-images-amazon.com/images/M/MV5BNjAwMjE2NDExNF5BMl5BanBnXkFtZTcwODAwODg4OQ@@._V1_SY1000_CR0,0,806,1000_AL_.jpg', None, None),
 (381, 'Young Benjen Stark', '/character/ch0153996/', 'Matteo Elezi', '/name/nm5502295/', 'CH_381', None, None, None, None, None),
 (383, 'Young Lyanna Stark', '/character/ch0543804/', 'Cordelia Hill', '/name/nm8108764/', 'CH_383', None, None, None, None, None),
 (386, 'Young Ned Stark', '/character/ch0154681/', 'Sebastian Croft', '/name/nm7509185/', 'CH_386', None, None, None, None, None)]

```2.``` Find all of the information about scenes in season 1, episode 1.

In [36]:
%sql select * from scenes where episodeNum=1 and seasonNum=1

 * mysql+pymysql://root:***@localhost/W4111GoTSolution
36 rows affected.

[(0, 1, 1, 1, '0:00:40', '0:01:45', 'The Wall', 'Castle Black', None, None, None, None),
 (1, 1, 1, 2, '0:01:45', '0:03:24', 'North of the Wall', 'The Haunted Forest', None, None, None, None),
 (2, 1, 1, 3, '0:03:24', '0:03:31', 'North of the Wall', 'The Haunted Forest', None, None, None, None),
 (3, 1, 1, 4, '0:03:31', '0:03:38', 'North of the Wall', 'The Haunted Forest', None, None, None, None),
 (4, 1, 1, 5, '0:03:38', '0:03:44', 'North of the Wall', 'The Haunted Forest', None, None, None, None),
 (5, 1, 1, 6, '0:03:44', '0:05:36', 'North of the Wall', 'The Haunted Forest', None, None, None, None),
 (6, 1, 1, 7, '0:05:36', '0:05:41', 'North of the Wall', 'The Haunted Forest', None, None, None, None),
 (7, 1, 1, 8, '0:05:41', '0:05:48', 'North of the Wall', 'The Haunted Forest', None, None, None, None),
 (8, 1, 1, 9, '0:05:48', '0:05:58', 'North of the Wall', 'The Haunted Forest', None, None, None, None),
 (9, 1, 1, 10, '0:05:58', '0:06:21', 'North of the Wall', 'The Haunted Forest', None, None, None, None),
 (10, 1, 1, 11, '0:06:21', '0:06:39', 'North of the Wall', 'The Haunted Forest', None, None, None, None),
 (11, 1, 1, 12, '0:06:39', '0:06:49', 'North of the Wall', 'The Haunted Forest', None, None, None, None),
 (12, 1, 1, 13, '0:06:49', '0:07:45', 'North of the Wall', 'The Haunted Forest', None, None, None, None),
 (13, 1, 1, 14, '0:09:27', '0:12:38', 'The North', 'Winterfell', None, None, None, None),
 (14, 1, 1, 15, '0:12:38', '0:15:41', 'The North', 'Outside Winterfell', None, None, None, None),
 (15, 1, 1, 16, '0:15:41', '0:18:44', 'The North', 'Outside Winterfell', None, None, None, None),
 (16, 1, 1, 17, '0:18:44', '0:20:45', 'The Crownlands', "King's Landing", None, None, None, None),
 (17, 1, 1, 18, '0:20:45', '0:22:43', 'The North', 'Winterfell', None, None, None, None),
 (18, 1, 1, 19, '0:22:43', '0:23:09', 'The North', 'Winterfell', None, None, None, None),
 (19, 1, 1, 20, '0:23:09', '0:23:39', 'The North', 'Winterfell', None, None, None, None),
 (20, 1, 1, 21, '0:23:39', '0:29:16', 'The North', 'Winterfell', None, None, None, None),
 (21, 1, 1, 22, '0:29:16', '0:30:47', 'The North', 'Winterfell', None, None, None, None),
 (22, 1, 1, 23, '0:30:47', '0:32:57', 'The North', 'Winterfell', None, None, None, None),
 (23, 1, 1, 24, '0:32:57', '0:33:45', 'The North', 'Winterfell', None, None, None, None),
 (24, 1, 1, 25, '0:33:45', '0:36:17', 'Pentos', None, None, None, None, None),
 (25, 1, 1, 26, '0:36:17', '0:38:23', 'Pentos', None, None, None, None, None),
 (26, 1, 1, 27, '0:38:23', '0:40:05', 'Pentos', None, None, None, None, None),
 (27, 1, 1, 28, '0:40:05', '0:40:56', 'The North', 'Winterfell', None, None, None, None),
 (28, 1, 1, 29, '0:40:56', '0:41:19', 'The North', 'Winterfell', None, None, None, None),
 (29, 1, 1, 30, '0:41:19', '0:44:14', 'The North', 'Winterfell', None, None, None, None),
 (30, 1, 1, 31, '0:44:14', '0:47:28', 'The North', 'Winterfell', None, None, None, None),
 (31, 1, 1, 32, '0:47:28', '0:50:29', 'The North', 'Winterfell', None, None, None, None),
 (32, 1, 1, 33, '0:50:29', '0:56:05', 'Pentos', None, None, None, None, None),
 (33, 1, 1, 34, '0:56:05', '0:57:48', 'Pentos', None, None, None, None, None),
 (34, 1, 1, 35, '0:57:48', '0:59:06', 'The North', 'Winterfell', None, None, None, None),
 (35, 1, 1, 36, '0:59:06', '1:00:57', 'The North', 'Winterfell', None, None, None, None)]

```3.``` Find all of the characters and actors who played them.

In [37]:
%%sql
SELECT
    character_id,
    (select characterName from characters where characters.character_id=
         characters_actors.character_id) as characterName,
    actorName, season
FROM W4111GoTSolution.characters_actors;

 * mysql+pymysql://root:***@localhost/W4111GoTSolution
(pymysql.err.ProgrammingError) (1146, "Table 'w4111gotsolution.characters_actors' doesn't exist")
[SQL: SELECT
    character_id,
    (select characterName from characters where characters.character_id=
         characters_actors.character_id) as characterName,
    actorName, season
FROM W4111GoTSolution.characters_actors;]
(Background on this error at: http://sqlalche.me/e/f405)

- Hmm. The season seems to be empty for some of the actors and some characters seem to be missing. Why?


- Let's look at the data to see which characters_actors the ```season``` is NULL.

In [33]:
%sql select * from characters_actors where season is NULL

 * mysql+pymysql://dbuser:***@localhost/W4111GoTSolution
0 rows affected.

[]

- That is not what I expected.


- This is an indication of why some cleanup is necessary.

## Data Cleanup

### Task

- CSV files are _text_ files, and all data is character strings.


- Spreadsheet applications, like Excel, and the data import tools in databases can _infer_ column types in some cases. For example, consider the table definition created for importing ```scenes_characters.```

```
CREATE TABLE `scenes_characters` (
  `id` int(11) DEFAULT NULL,
  `seasonNum` int(11) DEFAULT NULL,
  `episodeNum` int(11) DEFAULT NULL,
  `sceneNo` int(11) DEFAULT NULL,
  `characterName` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

```


- The import process inferred that some columns in the CSV file are text representations of integers, and performed conversion.


- The process is unreliable, and does not always work.


- For this task, you must modify column definitions and data valaues to represent the correct the meaning of the data. We will cover keys in the next task.


- Execute your DDL and DML SQL in cells below. You can add Markdown cells to explain what you are doing.


- My approach is to create a new schema with corrected table definitions and cleaned copies of the data. This preserves the original data for data lineage and avoids possible information loss.


- Call your new schema ```W4111GoTSolutionClean.```


- To help you, I provide an example for one table $-$ ```groups```


- __NOTE:__ You can use MySQL Workbench or other tools to help you write the DDL and DML statements, but you must execute the statements in the cells below.

- Create the schema.

In [36]:
%sql CREATE SCHEMA `W4111GoTSolutionClean` ;

 * mysql+pymysql://dbuser:***@localhost/W4111GoTSolution
1 rows affected.

[]

- What does ```groups``` look like?

In [38]:
%sql describe  W4111GotSolution.groups

 * mysql+pymysql://dbuser:***@localhost/W4111GoTSolution
3 rows affected.

[('id', 'int(11)', 'YES', '', None, ''),
 ('groupName', 'text', 'YES', '', None, ''),
 ('character', 'text', 'YES', '', None, '')]

In [41]:
%sql select min(length(groupName)) as min_group_name_len, max(length(groupName)) as max_group_name \
    from W4111GoTSolution.groups;

 * mysql+pymysql://dbuser:***@localhost/W4111GoTSolution
1 rows affected.

[(4, 13)]

In [45]:
%sql select min(length(`character`)) as min_character_name_len, max(length(`character`)) as max_character_name_len \
    from W4111GoTSolution.groups;

 * mysql+pymysql://dbuser:***@localhost/W4111GoTSolution
1 rows affected.

[(0, 21)]

- Create a table with clean data.

In [48]:
%%sql
create table W4111GotSolutionClean.groups (
    id int,
    groupName varchar(32),
    `characterName` varchar(32))

 * mysql+pymysql://dbuser:***@localhost/W4111GoTSolution
0 rows affected.

[]

In [49]:
%%sql
    insert into W4111GotSolutionClean.groups
        select id, groupName, `character` from W4111GotSolution.groups;

 * mysql+pymysql://dbuser:***@localhost/W4111GoTSolution
168 rows affected.

[]

In [50]:
%sql select count(*) from W4111GotSolution.groups

 * mysql+pymysql://dbuser:***@localhost/W4111GoTSolution
1 rows affected.

[(168,)]

- We successfully copied all of the rows and set reasonable data types.


- But,

In [51]:
%sql select count(*) from W4111GoTSolutionClean.groups where characterName=''

 * mysql+pymysql://dbuser:***@localhost/W4111GoTSolution
1 rows affected.

[(14,)]

- ```''``` is a common way to represent "unknown" or "not applicable" in text data.[Codd's Rule no. 3](https://www.webopedia.com/TERM/C/Codds_Rules.html) defines the systmatic treatment of unknown or  not applicable data.

In [52]:
%sql update W4111GoTSolutionClean.groups set characterName=NULL where characterName=''

 * mysql+pymysql://dbuser:***@localhost/W4111GoTSolution
14 rows affected.

[]

### Answers

__characters__

__character_relationships__

- There is some serialized JSON in the ```value``` column for ```actor.```


- Also, ```actor``` is redundant and we will need to remove later. It is here because we have to do some additional processing code to better align character relationships with scene information. We know ```character-actor``` mapping but until we factor in scenes, we are not sure which actor if there was more than one.

__characters_actors__

__episodes__

__locations__

__scenes__

__scenes_characters__

## Keys, Constraints and Integrity

### Task

- Correct analysis and management of the data requires defining keys and integrity constraints.


- Use DML statements to modify the schema to create the constraints you think best.


- The following diagram is my definition, but this is an example and may not be correct. It is simply to help you get started.

| <img src="./got_er_model.png"> |
| :---: |
|__GoT ER Model__ |

### Answer

__characters, characters_actors__

__characters_relationships__

__groups__

__locations__

__scenes__

__scenes_characters__

## View

Create the following views.

### Character and Locations

- Characters appear in ```scenes``` at ```locations.```


- Create a view of the form:
    - ```location```
    - ```character```
    - ```count``` of ```scenes``` with the ```character``` and the ```location.```
    - Only include ```characters``` that appeared in atleast 50 ```scenes.```
    
<u>Answer</u>

### Actors and Episodes

- Create the following view:
    - ```seasonNum```
    - ```episodeNum```
    - ```no_of_scenes,``` which is the count of scenes in which the character appeared
    - ```character_id```
    - ```character_name```
    - ```actor_name```
    - Ordered by ```seasonNum``` and ```characterNum``` ascending and ```no_of_scenes``` descending
    
<u>Answer</u>

### Character Interactions

- ```Characters``` interacted if they appeared in the same ```scene.```


- Create the following view:
    - ```characterName_1```
    - ```character_id_1```
    - ```characterName_2```
    - ```character_id_2```
    - ```scene_count,``` number of scenes containing both ```characters.```
    - Order by ```scene_count``` descending.

- Each pair should appear only once, that is the table should not contain two rows of the form:
    - ```character_1, character_2, scene_count```
    - ```character_2, character_1, scene_count```
    
    
<u>Answer</u>

### Interesting View 1

- Create a view of the information that you think would be interesting to fans.


- Explain what you view is producing.

<u>Answer</u>

- Explanation:

### Interesting View 2

- Create a view of the information that you think would be interesting to fans.


- Explain what you view is producing.

<u>Answer</u>

- Explanation:

# Programming

## Overview

- Ensuring that programming track students build core skills is essential. Programming track assignments will contain a subset of the broader, more complete tasks assigned in the No programming assignments. So, there is a common core section to the programming track homework.


- Additionally, the programming track will have tasks that reinforce skills necessary for programming and databases.


## Common Core

### Tasks

- Schema and DML: For the following tables, perform the data import, data cleanup and schema improvement takes for the following tables:
1. ```characters```
2. ```scenes```
3. ```scenes_characters```


- Views
    1. Implement the view in 3.5.3, "Character Interactions."
    2. Define, explain and implement a view of you choosing.
    
### Answers

<u>Data Import and Cleanup</u>

- Characters

In [28]:
%load_ext sql
%sql mysql+pymysql://root:Tiao2680230@localhost/W4111GoTSolution

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

'Connected: root@W4111GoTSolution'

In [124]:
import pymysql
from sqlalchemy import create_engine
def importcsv(f):
    url="Data/csv/"+f+".csv"
    csv=pd.read_csv(url)
    csv=csv.drop(['id'],axis=1)
    csv.to_sql(name=f, con=engine, if_exists='replace', index='id');

In [162]:
engine = create_engine('mysql+pymysql://root:Tiao2680230@localhost/W4111GoTSolution')

In [69]:
%sql CREATE SCHEMA `W4111GoTSolutionClean`;

   mysql+pymysql://root:***@localhost/W4111GoTSolution
 * mysql+pymysql://root:***@localhost/W4111GoTSolutionClean
(pymysql.err.ProgrammingError) (1007, "Can't create database 'W4111GoTSolutionClean'; database exists")
[SQL: CREATE SCHEMA `W4111GoTSolutionClean`;]
(Background on this error at: http://sqlalche.me/e/f405)

In [97]:
importcsv('characters')

- Scenes

In [165]:
importcsv('scenes')

- Scenes and Characters

In [168]:
importcsv('scenes_characters')

 * mysql+pymysql://root:***@localhost/W4111GoTSolution
   mysql+pymysql://root:***@localhost/W4111GoTSolutionClean
1 rows affected.

[(12114,)]

In [29]:
%%sql
drop table if exists W4111GoTSolution.character_ids;

CREATE TABLE `W4111GoTSolution`.`character_ids` (
  `auto_id` INT NOT NULL AUTO_INCREMENT,
  `characterName` VARCHAR(128) NULL,
  `real_id` INT NULL,
  `character_id` VARCHAR(16) GENERATED ALWAYS AS (concat("CH_", real_id)) STORED,
  PRIMARY KEY (`auto_id`));
  
  
insert into character_ids(characterName, real_id)
    select characterName, id from characters order by id asc;

insert into character_ids(characterName)
SELECT distinct characterName FROM W4111GoTSolution.scenes_characters
where  characterName not in (select characterName from characters);
                
update character_ids
set real_id = auto_id-1 where real_id is NULL;

 * mysql+pymysql://root:***@localhost/W4111GoTSolution
   mysql+pymysql://root:***@localhost/W4111GoTSolutionClean
0 rows affected.
0 rows affected.
389 rows affected.
238 rows affected.
238 rows affected.

[]

In [23]:
%load_ext sql
%sql mysql+pymysql://root:Tiao2680230@localhost/W4111GoTSolutionClean

'Connected: root@W4111GoTSolutionClean'

In [117]:
%%sql
drop table if exists characters;
create table W4111GotSolutionClean.characters (
    id int,
    characterName varchar(64),
    characterLink varchar(256),
    actorName varchar(32),
actorLink varchar(256),
character_id varchar(8),
royal varchar(8),
characterImageThumb varchar(256),
characterImageFull varchar(256),
nickname varchar(16),
kingsguard varchar(8));

   mysql+pymysql://root:***@localhost/W4111GoTSolution
 * mysql+pymysql://root:***@localhost/W4111GoTSolutionClean
   mysql+pymysql://root:***@localhost/W4111GoTSolutionClean2
0 rows affected.
0 rows affected.

[]

In [118]:
%%sql
drop table if exists scenes;
create table W4111GotSolutionClean.scenes (
    id int,
    seasonNum int,
    episodeNum int,
    sceneNo int,
sceneStart varchar(32),
sceneEnd varchar(32),
location varchar(32) ,
sublocation varchar(64),
greensight int,
altLocation varchar(32),
warg int,
flashback int)

   mysql+pymysql://root:***@localhost/W4111GoTSolution
 * mysql+pymysql://root:***@localhost/W4111GoTSolutionClean
   mysql+pymysql://root:***@localhost/W4111GoTSolutionClean2
0 rows affected.
0 rows affected.

[]

In [119]:
%%sql
drop table if exists scenes_characters;
create table W4111GotSolutionClean.scenes_characters (
    id int,
    seasonNum int,
    episodeNum int,
    sceneNo int,
characterName varchar(64))

   mysql+pymysql://root:***@localhost/W4111GoTSolution
 * mysql+pymysql://root:***@localhost/W4111GoTSolutionClean
   mysql+pymysql://root:***@localhost/W4111GoTSolutionClean2
0 rows affected.
0 rows affected.

[]

In [120]:
%sql describe W4111GoTSolutionClean.characters

   mysql+pymysql://root:***@localhost/W4111GoTSolution
 * mysql+pymysql://root:***@localhost/W4111GoTSolutionClean
   mysql+pymysql://root:***@localhost/W4111GoTSolutionClean2
11 rows affected.

[('id', 'int(11)', 'YES', '', None, ''),
 ('characterName', 'varchar(64)', 'YES', '', None, ''),
 ('characterLink', 'varchar(256)', 'YES', '', None, ''),
 ('actorName', 'varchar(32)', 'YES', '', None, ''),
 ('actorLink', 'varchar(256)', 'YES', '', None, ''),
 ('character_id', 'varchar(8)', 'YES', '', None, ''),
 ('royal', 'varchar(8)', 'YES', '', None, ''),
 ('characterImageThumb', 'varchar(256)', 'YES', '', None, ''),
 ('characterImageFull', 'varchar(256)', 'YES', '', None, ''),
 ('nickname', 'varchar(16)', 'YES', '', None, ''),
 ('kingsguard', 'varchar(8)', 'YES', '', None, '')]

In [121]:
%%sql
    insert into W4111GotSolutionClean.characters
        select * from W4111GotSolution.characters;

   mysql+pymysql://root:***@localhost/W4111GoTSolution
 * mysql+pymysql://root:***@localhost/W4111GoTSolutionClean
   mysql+pymysql://root:***@localhost/W4111GoTSolutionClean2
389 rows affected.

[]

In [122]:
%%sql
    insert into W4111GotSolutionClean.scenes
        select * from W4111GotSolution.scenes;

   mysql+pymysql://root:***@localhost/W4111GoTSolution
 * mysql+pymysql://root:***@localhost/W4111GoTSolutionClean
   mysql+pymysql://root:***@localhost/W4111GoTSolutionClean2
4165 rows affected.

[]

In [123]:
%%sql
    insert into W4111GotSolutionClean.scenes_characters
        select * from W4111GotSolution.scenes_characters;

   mysql+pymysql://root:***@localhost/W4111GoTSolution
 * mysql+pymysql://root:***@localhost/W4111GoTSolutionClean
   mysql+pymysql://root:***@localhost/W4111GoTSolutionClean2
12114 rows affected.

[]

In [124]:
%sql select count(*) from W4111GoTSolutionClean.characters where royal=''

   mysql+pymysql://root:***@localhost/W4111GoTSolution
 * mysql+pymysql://root:***@localhost/W4111GoTSolutionClean
   mysql+pymysql://root:***@localhost/W4111GoTSolutionClean2
1 rows affected.

[(0,)]

<u>Keys and Constraints</u>

- Characters

In [125]:
%%sql 
ALTER TABLE `characters` ADD PRIMARY KEY (`character_id`)

   mysql+pymysql://root:***@localhost/W4111GoTSolution
 * mysql+pymysql://root:***@localhost/W4111GoTSolutionClean
   mysql+pymysql://root:***@localhost/W4111GoTSolutionClean2
0 rows affected.

[]

Select character_id as the PK

- Scenes

In [127]:
%%sql 
ALTER TABLE `scenes` ADD PRIMARY KEY (seasonNum,episodeNum,sceneNo)

   mysql+pymysql://root:***@localhost/W4111GoTSolution
 * mysql+pymysql://root:***@localhost/W4111GoTSolutionClean
   mysql+pymysql://root:***@localhost/W4111GoTSolutionClean2
0 rows affected.

[]

Select seasonNum,episodeNum,sceneNo as the PK

- Scenes and Characters

In [130]:
%%sql 
ALTER TABLE `scenes_characters` ADD PRIMARY KEY (seasonNum,episodeNum,sceneNo,characterName)

   mysql+pymysql://root:***@localhost/W4111GoTSolution
 * mysql+pymysql://root:***@localhost/W4111GoTSolutionClean
   mysql+pymysql://root:***@localhost/W4111GoTSolutionClean2
0 rows affected.

[]

In [132]:
%%sql
ALTER TABLE `scenes_characters` add constraint FOREIGN KEY (seasonNum,episodeNum,sceneNo)
references scenes(seasonNum,episodeNum,sceneNo)

   mysql+pymysql://root:***@localhost/W4111GoTSolution
 * mysql+pymysql://root:***@localhost/W4111GoTSolutionClean
   mysql+pymysql://root:***@localhost/W4111GoTSolutionClean2
12114 rows affected.

[]

Select seasonNum,episodeNum,sceneNo,characterName as the PK. 

seasonNum,episodeNum,sceneNo those three are foreign key in scenes_characters references on scenes

<u>Views</u>

- Character Interaction Views

In [14]:
%%sql
drop view if exists cha_relation;
create view cha_relation as
select s1.seasonNum,s1.episodeNum,s1.sceneNo,s1.characterName as Name1,s2.characterName as Name2 
from scenes_characters s1 inner join scenes_characters s2
on s1.seasonNum=s2.seasonNum and s1.episodeNum=s2.episodeNum and
s1.sceneNo=s2.sceneNo;

 * mysql+pymysql://root:***@localhost/W4111GoTSolutionClean
0 rows affected.
0 rows affected.

[]

In [15]:
%sql select * from cha_relation limit 10

 * mysql+pymysql://root:***@localhost/W4111GoTSolutionClean
10 rows affected.

[(1, 1, 1, 'Gared', 'Gared'),
 (1, 1, 1, 'Gared', 'Waymar Royce'),
 (1, 1, 1, 'Gared', 'Will'),
 (1, 1, 1, 'Waymar Royce', 'Gared'),
 (1, 1, 1, 'Waymar Royce', 'Waymar Royce'),
 (1, 1, 1, 'Waymar Royce', 'Will'),
 (1, 1, 1, 'Will', 'Gared'),
 (1, 1, 1, 'Will', 'Waymar Royce'),
 (1, 1, 1, 'Will', 'Will'),
 (1, 1, 2, 'Gared', 'Gared')]

In [16]:
%sql drop view if exists cha_relation1;\
create view cha_relation1 as\
select Name1,Name2,count(*) as num from cha_relation\
where Name1!=Name2\
group by Name1,Name2;

 * mysql+pymysql://root:***@localhost/W4111GoTSolutionClean
0 rows affected.
0 rows affected.

[]

In [4]:
%sql select * from cha_relation1\
limit 10

 * mysql+pymysql://root:***@localhost/W4111GoTSolutionClean
10 rows affected.

[('Gared', 'Waymar Royce', 5),
 ('Gared', 'Will', 4),
 ('Waymar Royce', 'Gared', 5),
 ('Waymar Royce', 'Will', 3),
 ('Will', 'Gared', 4),
 ('Will', 'Waymar Royce', 3),
 ('Wight Wildling Girl', 'Will', 2),
 ('Will', 'Wight Wildling Girl', 2),
 ('Gared', 'White Walker', 2),
 ('Waymar Royce', 'White Walker', 1)]

In [17]:
%%sql 
create view characters_interaction as
(select * from
(select Name1,id1,Name2,id as id2,num from 
(select Name1,Name2,num,c2.id as id1 from cha_relation1 c1 inner join characters c2 on c1.Name1=c2.characterName) bindt
inner join characters c3 on bindt.Name2=c3.characterName) t3
where id1<id2
order by num desc)

 * mysql+pymysql://root:***@localhost/W4111GoTSolutionClean
0 rows affected.

[]

In [19]:
%%sql 
select * from characters_interaction
limit 10

 * mysql+pymysql://root:***@localhost/W4111GoTSolutionClean
10 rows affected.

[('Daenerys Targaryen', 44, 'Drogon', 57, 172),
 ('Daenerys Targaryen', 44, 'Jorah Mormont', 125, 148),
 ('Jon Snow', 123, 'Tormund Giantsbane', 345, 145),
 ('Lord Varys', 177, 'Tyrion Lannister', 349, 141),
 ('Davos Seaworth', 47, 'Jon Snow', 123, 136),
 ('Daenerys Targaryen', 44, 'Missandei', 216, 131),
 ('Daenerys Targaryen', 44, 'Jon Snow', 123, 119),
 ('Daenerys Targaryen', 44, 'Tyrion Lannister', 349, 116),
 ('Missandei', 216, 'Tyrion Lannister', 349, 97),
 ('Brienne of Tarth', 31, 'Jaime Lannister', 113, 91)]

- Your View and Explanation

View characters_interaction is my final result, I join the scenes_characters itself by itselves and filter out the repeating row and finally join this to table characters to search their id.

## Programming

### Data Processing and Cleansing

#### Task

- The ```scene``` information in ```episodes.json``` complements and extend some of the information about character interactions and relationships. An example is:

```
            {
               "sceneStart":"0:50:24",
               "sceneEnd":"0:55:54",
               "location":"The Crownlands",
               "subLocation":"King's Landing",
               "characters":[
                  {
                     "name":"Arya Stark",
                     "weapon":[
                        {"action":"has", "name":"Needle"}
                     ]
                  },
                  {
                     "name":"Eddard Stark",
                     "title":"Hand",
                     "alive":false,
                     "mannerOfDeath":"Decapitation",
                     "killedBy":[
                        "Ilyn Payne"
                     ]
                  },
                  {"name":"Yoren"},
                  {"name":"Sansa Stark"},
                  {"name":"Petyr Baelish"},
                  {"name":"Cersei Lannister"},
                  {"name":"Joffrey Baratheon", "title":"King"},
                  {"name":"Grand Maester Pycelle"},
                  {"name":"Lord Varys"},
                  {"name":"Sandor Clegane"},
                  {
                     "name":"Ilyn Payne",
                     "weapon":[
                        {"action":"has", "name":"Ice"}
                     ]
                  }
               ]
            }
         ]
```


- A little data processing determines that the top-level elements of a ```character``` in a scene are:

```Top level keys in characters in scenes are:
	 sex
	 name
	 weapon
	 born
	 married
	 killedBy
	 mannerOfDeath
	 title
	 alive
```

- Your data processing and cleanse tasks is to create a table of the form:
    - ```seasonNum```
    - ```episodeNum```
    - ```sceneNo```
    - ```character_id_1```
    - ```action```
    - ```character_id_2```
    
    
- You can get access to information that maps ```characterName``` to ```character_id``` using the following code.

In [303]:
cloud_conn = pymysql.connect(
    host="columbia8013.cqgsme1nmjms.us-east-1.rds.amazonaws.com",
    user="gotuser",
    password="gotusergotuser",
    db="W4111GoTSolutionClean",
    cursorclass=pymysql.cursors.DictCursor)

In [304]:
def get_character_info(c_name):
    
    sql = "select * from characters where characterName=%s"
    cur = cloud_conn.cursor()
    res = cur.execute(sql, (c_name))
    res = cur.fetchall()
    return res

In [320]:
get_character_info("White Walker")

[{'id': 362,
  'characterName': 'White Walker',
  'characterLink': '/character/ch0304921/',
  'actorName': 'Ian Whyte',
  'actorLink': '/name/nm1613839/',
  'character_id': 'CH_362',
  'royal': 0,
  'characterImageThumb': 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjYzNDMyZWUtMDVlMy00OGQxLWFkZTctOWMxZDk1MDA5MmQzXkEyXkFqcGdeQXVyMjk3NTUyOTc@._V1._SX100_SY140_.jpg',
  'characterImageFull': 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjYzNDMyZWUtMDVlMy00OGQxLWFkZTctOWMxZDk1MDA5MmQzXkEyXkFqcGdeQXVyMjk3NTUyOTc@._V1_.jpg',
  'nickname': None,
  'kingsguard': 0},
 {'id': 363,
  'characterName': 'White Walker',
  'characterLink': '/character/ch0304921/',
  'actorName': 'Ross Mullan',
  'actorLink': '/name/nm1368643/',
  'character_id': 'CH_363',
  'royal': 0,
  'characterImageThumb': 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjYzNDMyZWUtMDVlMy00OGQxLWFkZTctOWMxZDk1MDA5MmQzXkEyXkFqcGdeQXVyMjk3NTUyOTc@._V1._SX100_SY140_.jpg',
  'characterImageFull': 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjYzNDMyZWUtMDVlMy00OGQxLWFkZTctOWMxZDk1MDA5MmQzXkEyXkFqcGdeQXVyMjk3NTUyOTc@._V1_.jpg',
  'nickname': None,
  'kingsguard': 0},
 {'id': 364,
  'characterName': 'White Walker',
  'characterLink': '/character/ch0304921/',
  'actorName': 'Tim Loane',
  'actorLink': '/name/nm0516385/',
  'character_id': 'CH_364',
  'royal': 0,
  'characterImageThumb': 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjYzNDMyZWUtMDVlMy00OGQxLWFkZTctOWMxZDk1MDA5MmQzXkEyXkFqcGdeQXVyMjk3NTUyOTc@._V1._SX100_SY140_.jpg',
  'characterImageFull': 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjYzNDMyZWUtMDVlMy00OGQxLWFkZTctOWMxZDk1MDA5MmQzXkEyXkFqcGdeQXVyMjk3NTUyOTc@._V1_.jpg',
  'nickname': None,
  'kingsguard': 0}]

In [319]:
get_character_info(relation['name'].iloc[253])[0]['id']

44

#### Answer

<u>Table Definition</u>

In [76]:
%sql CREATE SCHEMA `W4111GoTSolutionClean2`;

   mysql+pymysql://root:***@localhost/W4111GoTSolution
 * mysql+pymysql://root:***@localhost/W4111GoTSolutionClean
1 rows affected.

[]

In [77]:
%load_ext sql
%sql mysql+pymysql://root:Tiao2680230@localhost/W4111GoTSolutionClean2

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

'Connected: root@W4111GoTSolutionClean2'

In [343]:
import json
import pymysql
from pandas.io.json import json_normalize
from math import isnan
import math
import pandas as pd
#db = pymysql.connect("localhost","root","Tiao2680230","W4111GoTSolutionClean2",use_unicode=True, charset="utf8")
#cursor = db.cursor()
#sql = """ DROP TABLE IF EXISTS characters """
#cursor.execute(sql)


with open('Data/json/episodes.json') as f:
    data=json.load(f)
data=data['episodes']

final=[j for i in [y['characters'] for x in [z['scenes'] for z in data] for y in x] for j in i]        
relation1=json_normalize(final)[['name','killedBy','married.to']]
relation=relation1[relation1['killedBy'].notna()|relation1['married.to'].notna()]
#display(relation)
#for i in relation['killedBy']
#[i[0] for i in relation['killedBy'] if i.notnull()==True]

for i in range(len(relation['killedBy'])):
    if type(relation['killedBy'].iloc[i])==list:
        if relation['killedBy'].iloc[i]!=[]:
            relation['killedBy'].iloc[i]=relation['killedBy'].iloc[i][0]
        else:
            relation['killedBy'].iloc[i]=math.nan
relation=relation[relation['killedBy'].notna()|relation['married.to'].notna()]
#json_normalize([y['characters'] for y in [z['scenes'] for z in data][0]])[['name','killedBy','married.to']]
#[x['characters'] for x in y for y in z['scenes'] for z in data]
df=relation.rename(columns={'name': 'name','married.to':'marriedto'})
scenenum=df.index
df=pd.melt(df,id_vars=['name'],value_vars=['killedBy','marriedto'])
df=df[df['value'].notna()]
df.index=scenenum
df=df.rename(columns={'name': 'name','variable':'relationship','value':'name2'})
df

/Users/zjh/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Users/zjh/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

                    name relationship              name2
17          Waymar Royce     killedBy       White Walker
23                 Gared     killedBy       White Walker
37                  Will     killedBy       Eddard Stark
58             Jon Arryn     killedBy         Lysa Arryn
129     Catspaw Assassin     killedBy             Summer
...                  ...          ...                ...
11845    Margaery Tyrell    marriedto   Tommen Baratheon
11846        Sansa Stark    marriedto        Ramsay Snow
11871        Ramsay Snow    marriedto        Sansa Stark
11872       Lyanna Stark    marriedto  Rhaegar Targaryen
11974  Rhaegar Targaryen    marriedto       Lyanna Stark

[253 rows x 3 columns]

In [344]:
%load_ext sql
%sql mysql+pymysql://root:Tiao2680230@localhost/W4111GoTSolutionClean2

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

'Connected: root@W4111GoTSolutionClean2'

In [345]:
%%sql
drop table if exists relationship;
create table W4111GotSolutionClean2.relationship (
    id int,
    name varchar(64),
    relationship varchar(64),
    name2 varchar(64))

   mysql+pymysql://root:***@localhost/W4111GoTSolutionClean
 * mysql+pymysql://root:***@localhost/W4111GoTSolutionClean2
0 rows affected.
0 rows affected.

[]

In [346]:
engine1 = create_engine('mysql+pymysql://root:Tiao2680230@localhost/W4111GoTSolutionClean2')
#csv=relation.drop(['id'],axis=1)
df.to_sql(name='relationship', con=engine1, if_exists='replace', index='id');

<u>Sample Query</u>

In [30]:
%%sql select t1.*,c.character_id as characterid1,c2.character_id as characterid2 from
(select seasonNum,episodeNum,sceneNo,r.* from W4111GoTSolutionClean2.relationship r
inner join W4111GoTSolutionClean.scenes_characters s on r.id=s.id) t1
left join W4111GoTSolution.character_ids c on t1.name=c.characterName
left join W4111GoTSolution.character_ids c2 on t1.name2=c2.characterName
order by id

 * mysql+pymysql://root:***@localhost/W4111GoTSolution
   mysql+pymysql://root:***@localhost/W4111GoTSolutionClean
274 rows affected.

[(1, 1, 10, 17, 'Waymar Royce', 'killedBy', 'White Walker', 'CH_360', 'CH_362'),
 (1, 1, 10, 17, 'Waymar Royce', 'killedBy', 'White Walker', 'CH_360', 'CH_363'),
 (1, 1, 10, 17, 'Waymar Royce', 'killedBy', 'White Walker', 'CH_360', 'CH_364'),
 (1, 1, 13, 23, 'Gared', 'killedBy', 'White Walker', 'CH_68', 'CH_362'),
 (1, 1, 13, 23, 'Gared', 'killedBy', 'White Walker', 'CH_68', 'CH_363'),
 (1, 1, 13, 23, 'Gared', 'killedBy', 'White Walker', 'CH_68', 'CH_364'),
 (1, 1, 15, 37, 'Will', 'killedBy', 'Eddard Stark', 'CH_368', 'CH_59'),
 (1, 1, 17, 58, 'Jon Arryn', 'killedBy', 'Lysa Arryn', 'CH_122', 'CH_184'),
 (1, 1, 33, 129, 'Catspaw Assassin', 'killedBy', 'Summer', 'CH_37', 'CH_326'),
 (1, 1, 33, 130, 'Mycah', 'killedBy', 'Sandor Clegane', 'CH_227', 'CH_299'),
 (1, 2, 13, 202, 'Lady', 'killedBy', 'Eddard Stark', 'CH_150', 'CH_59'),
 (1, 2, 26, 252, 'Hugh of the Vale', 'killedBy', 'Gregor Clegane', 'CH_106', 'CH_87'),
 (1, 2, 30, 261, 'Jory Cassel', 'killedBy', 'Jaime Lannister', 'CH_126', 'CH_113'),
 (1, 4, 26, 450, 'Stiv', 'killedBy', 'Theon Greyjoy', 'CH_324', 'CH_336'),
 (1, 5, 28, 547, 'Wallen', 'killedBy', 'Robb Stark', 'CH_358', 'CH_286'),
 (1, 6, 6, 567, 'Vardis Egen', 'killedBy', 'Bronn', 'CH_352', 'CH_32'),
 (1, 6, 6, 568, 'Viserys Targaryen', 'killedBy', 'Khal Drogo', 'CH_355', 'CH_133'),
 (1, 6, 15, 607, 'Robert Baratheon', 'killedBy', 'Boar', 'CH_287', None),
 (1, 6, 19, 626, 'Vayon Poole', 'killedBy', 'Lannister Guard', 'CH_513', 'CH_524'),
 (1, 7, 22, 712, 'Syrio Forel', 'killedBy', 'Meryn Trant', 'CH_327', 'CH_211'),
 (1, 8, 4, 734, 'Red Keep Stableboy', 'killedBy', 'Arya Stark', 'CH_274', 'CH_15'),
 (1, 8, 6, 737, 'Othor', 'killedBy', 'Jon Snow', 'CH_255', 'CH_123'),
 (1, 8, 9, 744, 'Mago', 'killedBy', 'Khal Drogo', 'CH_192', 'CH_133'),
 (1, 8, 21, 781, 'Qotho', 'killedBy', 'Jorah Mormont', 'CH_265', 'CH_125'),
 (1, 8, 23, 796, 'Eddard Stark', 'killedBy', 'Ilyn Payne', 'CH_59', 'CH_108'),
 (1, 9, 15, 905, 'Khal Drogo', 'killedBy', 'Daenerys Targaryen', 'CH_133', 'CH_44'),
 (1, 9, 25, 939, 'Mirri Maz Duur', 'killedBy', 'Daenerys Targaryen', 'CH_215', 'CH_44'),
 (1, 10, 22, 1028, 'Maester Cressen', 'killedBy', 'Maester Cressen', 'CH_187', 'CH_187'),
 (1, 10, 31, 1055, 'Barra', 'killedBy', 'Janos Slynt', 'CH_519', 'CH_114'),
 (2, 1, 18, 1127, 'Yoren', 'killedBy', 'Amory Lorch', 'CH_380', 'CH_8'),
 (2, 1, 27, 1152, 'Lommy Greenhands', 'killedBy', 'Polliver', 'CH_173', 'CH_259'),
 (2, 3, 7, 1264, 'Rennick', 'killedBy', 'Grey Wind', 'CH_523', 'CH_90'),
 (2, 3, 7, 1265, 'Tortured Prisoner', 'killedBy', 'The Tickler', 'CH_526', 'CH_333'),
 (2, 3, 28, 1324, 'Renly Baratheon', 'killedBy', 'Melisandre', 'CH_277', 'CH_208'),
 (2, 3, 29, 1332, 'The Tickler', 'killedBy', "Jaqen H'ghar", 'CH_333', 'CH_115'),
 (2, 4, 1, 1341, 'Rodrik Cassel', 'killedBy', 'Theon Greyjoy', 'CH_290', 'CH_336'),
 (2, 4, 28, 1426, 'High Septon', 'killedBy', "King's Landing Mob", 'CH_98', None),
 (2, 4, 28, 1426, 'High Septon', 'killedBy', "King's Landing Mob", 'CH_99', None),
 (2, 5, 1, 1449, "King's Landing Rioter #1", 'killedBy', 'Sandor Clegane', 'CH_140', 'CH_299'),
 (2, 5, 38, 1558, "King's Landing Rioter #2", 'killedBy', 'Sandor Clegane', 'CH_141', 'CH_299'),
 (2, 6, 6, 1580, "King's Landing Rioter #3", 'killedBy', 'Sandor Clegane', 'CH_142', 'CH_299'),
 (2, 6, 17, 1634, 'Amory Lorch', 'killedBy', "Jaqen H'ghar", 'CH_8', 'CH_115'),
 (2, 6, 24, 1653, 'Drennan', 'killedBy', 'Osha', 'CH_56', 'CH_253'),
 (2, 6, 24, 1654, 'Irri', 'killedBy', 'Doreah', 'CH_109', 'CH_53'),
 (2, 6, 24, 1655, 'Alton Lannister', 'killedBy', 'Jaime Lannister', 'CH_6', 'CH_113'),
 (2, 6, 33, 1677, 'Torrhen Karstark', 'killedBy', 'Jaime Lannister', 'CH_531', 'CH_113'),
 (2, 6, 43, 1702, 'Spice King', 'killedBy', 'Pyat Pree', 'CH_315', 'CH_261'),
 (2, 6, 46, 1715, 'Silk King', 'killedBy', 'Pyat Pree', 'CH_313', 'CH_261'),
 (2, 7, 26, 1784, 'Matthos Seaworth', 'killedBy', 'Bronn', 'CH_204', 'CH_32'),
 (2, 7, 27, 1788, 'Mandon Moore', 'killedBy', 'Podrick Payne', 'CH_196', 'CH_258'),
 (2, 7, 29, 1792, 'Soldier Tom', 'killedBy', 'Brienne of Tarth', 'CH_534', 'CH_31'),
 (2, 7, 29, 1794, 'Stark Soldier', 'killedBy', 'Brienne of Tarth', 'CH_535', 'CH_31'),
 (2, 9, 45, 2041, 'Maester Luwin', 'killedBy', 'Osha', 'CH_188', 'CH_253'),
 (2, 9, 115, 2152, 'Pyat Pree', 'killedBy', 'Daenerys Targaryen', 'CH_261', 'CH_44'),
 (2, 10, 8, 2209, 'Qhorin Halfhand', 'killedBy', 'Jon Snow', 'CH_264', 'CH_123'),
 (2, 10, 8, 2210, 'Xaro Xhoan Daxos', 'killedBy', 'Daenerys Targaryen', 'CH_375', 'CH_44'),
 (2, 10, 17, 2234, 'Doreah', 'killedBy', 'Daenerys Targaryen', 'CH_53', 'CH_44'),
 (2, 10, 17, 2235, 'Man of the Nightswatch', 'killedBy', 'White Walker', 'CH_536', 'CH_362'),
 (2, 10, 17, 2235, 'Man of the Nightswatch', 'killedBy', 'White Walker', 'CH_536', 'CH_363'),
 (2, 10, 17, 2235, 'Man of the Nightswatch', 'killedBy', 'White Walker', 'CH_536', 'CH_364'),
 (2, 10, 28, 2267, 'White Walker', 'killedBy', 'Jeor Mormont', 'CH_362', 'CH_118'),
 (2, 10, 28, 2267, 'White Walker', 'killedBy', 'Jeor Mormont', 'CH_363', 'CH_118'),
 (2, 10, 28, 2267, 'White Walker', 'killedBy', 'Jeor Mormont', 'CH_364', 'CH_118'),
 (2, 10, 34, 2285, 'Master Torturer', 'killedBy', 'Ramsay Snow', 'CH_540', 'CH_269'),
 (2, 10, 35, 2288, 'Craster', 'killedBy', 'Karl Tanner', 'CH_42', 'CH_128'),
 (2, 10, 38, 2300, 'Jeor Mormont', 'killedBy', 'Rast', 'CH_118', 'CH_271'),
 (2, 10, 38, 2304, 'Kraznys mo Nakloz', 'killedBy', 'Daenerys Targaryen', 'CH_148', 'CH_44'),
 (3, 1, 3, 2327, 'Beric Dondarrion', 'killedBy', 'Sandor Clegane', 'CH_21', 'CH_299'),
 (3, 1, 6, 2334, 'Martyn Lannister', 'killedBy', 'Rickard Karstark', 'CH_202', 'CH_283'),
 (3, 3, 36, 2728, 'Willem Lannister', 'killedBy', 'Rickard Karstark', 'CH_369', 'CH_283'),
 (3, 4, 33, 2834, 'Rickard Karstark', 'killedBy', 'Robb Stark', 'CH_283', 'CH_286'),
 (3, 4, 36, 2845, 'Ros', 'killedBy', 'Joffrey Baratheon', 'CH_293', 'CH_120'),
 (3, 4, 44, 2883, 'Mero', 'killedBy', 'Daario Naharis', 'CH_210', 'CH_43'),
 (3, 5, 1, 2903, 'Prendahl na Ghezn', 'killedBy', 'Daario Naharis', 'CH_260', 'CH_43'),
 (3, 5, 14, 2943, 'White Walker', 'killedBy', 'Samwell Tarly', 'CH_362', 'CH_298'),
 (3, 5, 14, 2943, 'White Walker', 'killedBy', 'Samwell Tarly', 'CH_363', 'CH_298'),
 (3, 5, 14, 2943, 'White Walker', 'killedBy', 'Samwell Tarly', 'CH_364', 'CH_298'),
 (3, 5, 14, 2944, 'Old Man', 'killedBy', 'Ygritte', 'CH_556', 'CH_378'),
 (3, 5, 18, 2962, 'Orell', 'killedBy', 'Jon Snow', 'CH_251', 'CH_123'),
 (3, 6, 23, 3081, 'Wendel Manderly', 'killedBy', 'Walder Frey', 'CH_557', 'CH_357'),
 (3, 8, 19, 3258, 'Grey Wind', 'killedBy', 'Frey Soldiers', 'CH_90', None),
 (3, 8, 19, 3259, 'Talisa Maegyr', 'killedBy', 'Lothar Frey', 'CH_328', 'CH_179'),
 (3, 8, 43, 3340, 'Robb Stark', 'killedBy', 'Roose Bolton', 'CH_286', 'CH_291'),
 (3, 8, 43, 3341, 'Catelyn Stark', 'killedBy', 'Black Walder Rivers', 'CH_36', 'CH_25'),
 (3, 8, 49, 3358, 'Joyeuse Erenford', 'killedBy', 'Catelyn Stark', 'CH_127', 'CH_36'),
 (3, 9, 25, 3446, 'Frey Soldier #1', 'killedBy', 'Arya Stark', 'CH_561', 'CH_15'),
 (3, 9, 29, 3462, 'Frey Soldier #2', 'killedBy', 'Sandor Clegane', 'CH_562', 'CH_299'),
 (3, 9, 37, 3484, 'Polliver', 'killedBy', 'Arya Stark', 'CH_259', 'CH_15'),
 (3, 9, 37, 3485, 'Tansy', 'killedBy', "Ramsay's hounds", 'CH_571', None),
 (3, 9, 60, 3586, 'Axell Florent', 'killedBy', 'Melisandre', 'CH_572', 'CH_208'),
 (3, 9, 65, 3593, 'Joffrey Baratheon', 'killedBy', 'Olenna Tyrell', 'CH_120', 'CH_248'),
 (3, 9, 68, 3600, 'Dontos Hollard', 'killedBy', 'Petyr Baelish', 'CH_51', 'CH_257'),
 (3, 9, 70, 3609, 'Guymon', 'killedBy', 'Ygritte', 'CH_579', 'CH_378'),
 (3, 9, 71, 3611, "Olly's Mother", 'killedBy', 'Styr', 'CH_580', 'CH_325'),
 (3, 9, 71, 3613, 'Oznak zo Pahl', 'killedBy', 'Daario Naharis', 'CH_581', 'CH_43'),
 (3, 10, 28, 3699, 'Locke', 'killedBy', 'Hodor', 'CH_171', 'CH_102'),
 (3, 10, 28, 3700, 'Karl Tanner', 'killedBy', 'Jon Snow', 'CH_128', 'CH_123'),
 (4, 1, 55, 3918, 'Rast', 'killedBy', 'Ghost', 'CH_271', 'CH_72'),
 (4, 2, 1, 3921, 'Old Man', 'killedBy', 'Sandor Clegane', 'CH_556', 'CH_299'),
 (4, 2, 6, 3932, 'Biter', 'killedBy', 'Sandor Clegane', 'CH_23', 'CH_299'),
 (4, 2, 6, 3935, 'Rorge', 'killedBy', 'Arya Stark', 'CH_292', 'CH_15'),
 (4, 2, 23, 4003, 'Lysa Arryn', 'killedBy', 'Petyr Baelish', 'CH_184', 'CH_257'),
 (4, 2, 45, 4107, "Mole's Town Whore", 'killedBy', 'Ygritte', 'CH_576', 'CH_378'),
 (4, 2, 45, 4108, 'Kegs', 'killedBy', 'Styr', 'CH_131', 'CH_325'),
 (4, 2, 81, 4306, 'Black Jack Bulwer', 'killedBy', 'Tormund Giantsbane', 'CH_594', 'CH_345'),
 (4, 3, 8, 4335, 'Mully', 'killedBy', 'Styr', 'CH_595', 'CH_325'),
 (4, 3, 38, 4429, 'Ralf Kenning', 'killedBy', 'Adrack Humble', 'CH_596', 'CH_597'),
 (4, 3, 39, 4432, 'Adrack Humble', 'killedBy', 'Ramsay Snow', 'CH_597', 'CH_269'),
 (4, 3, 54, 4501, 'Oberyn Martell', 'killedBy', 'Gregor Clegane', 'CH_245', 'CH_87'),
 (4, 5, 16, 4690, 'Pypar', 'killedBy', 'Ygritte', 'CH_262', 'CH_378'),
 (4, 5, 16, 4691, 'Thenn Warg', 'killedBy', 'Samwell Tarly', 'CH_335', 'CH_298'),
 (4, 5, 40, 4753, 'Styr', 'killedBy', 'Jon Snow', 'CH_325', 'CH_123'),
 (4, 5, 45, 4766, 'Ygritte', 'killedBy', 'Olly', 'CH_378', 'CH_249'),
 (4, 5, 48, 4776, 'Grenn', 'killedBy', 'Mag the Mighty', 'CH_89', 'CH_190'),
 (4, 7, 4, 4957, 'Donnel Hill', 'killedBy', 'Mag the Mighty', 'CH_600', 'CH_190'),
 (4, 7, 5, 4960, 'Cooper', 'killedBy', 'Mag the Mighty', 'CH_601', 'CH_190'),
 (4, 7, 6, 4963, 'Mag the Mighty', 'killedBy', 'Grenn', 'CH_190', 'CH_89'),
 (4, 7, 27, 5021, 'Jojen Reed', 'killedBy', 'Meera Reed', 'CH_121', 'CH_205'),
 (4, 8, 3, 5034, 'Shae', 'killedBy', 'Tyrion Lannister', 'CH_309', 'CH_349'),
 (4, 8, 3, 5035, 'Tywin Lannister', 'killedBy', 'Tyrion Lannister', 'CH_350', 'CH_349'),
 (4, 8, 3, 5036, 'White Rat', 'killedBy', 'Son of the Harpy', 'CH_604', 'CH_609'),
 (4, 8, 3, 5037, 'Mance Rayder', 'killedBy', 'Jon Snow', 'CH_195', 'CH_123'),
 (4, 8, 11, 5056, 'Eyrie Guard', 'killedBy', 'Brienne of Tarth', 'CH_608', 'CH_31'),
 (4, 8, 13, 5061, 'Son of the Harpy', 'killedBy', 'Mossador', 'CH_609', 'CH_218'),
 (4, 8, 33, 5129, 'Mossador', 'killedBy', 'Daario Naharis', 'CH_218', 'CH_43'),
 (4, 9, 41, 5243, 'Despondent Man', 'killedBy', "Jaqen H'ghar", 'CH_616', 'CH_115'),
 (4, 9, 53, 5270, 'Janos Slynt', 'killedBy', 'Jon Snow', 'CH_114', 'CH_123'),
 (4, 9, 75, 5313, 'Lead Dornish Guard', 'killedBy', 'Bronn', 'CH_158', 'CH_32'),
 (4, 9, 77, 5320, 'Merchant Captain', 'killedBy', 'Obara Sand', 'CH_209', 'CH_244'),
 (4, 9, 85, 5332, 'Second Son', 'killedBy', 'Son of the Harpy', 'CH_637', 'CH_609'),
 (4, 9, 85, 5333, 'Barristan Selmy', 'killedBy', 'Sons of the Harpy', 'CH_19', None),
 (4, 9, 85, 5334, 'Great Master #1', 'killedBy', 'Daenerys Targaryen', 'CH_79', 'CH_44'),
 (4, 9, 85, 5335, 'Ghita', 'killedBy', 'Arya Stark', 'CH_640', 'CH_15'),
 (4, 10, 26, 5422, 'Old Woman', 'killedBy', 'Ramsay Snow', 'CH_617', 'CH_269'),
 (4, 10, 38, 5458, 'Rattleshirt', 'killedBy', 'Tormund Giantsbane', 'CH_272', 'CH_345'),
 (4, 10, 40, 5461, 'Loboda', 'killedBy', 'White Walker', 'CH_170', 'CH_362'),
 (4, 10, 40, 5461, 'Loboda', 'killedBy', 'White Walker', 'CH_170', 'CH_363'),
 (4, 10, 40, 5461, 'Loboda', 'killedBy', 'White Walker', 'CH_170', 'CH_364'),
 (5, 1, 9, 5485, 'White Walker', 'killedBy', 'Jon Snow', 'CH_362', 'CH_123'),
 (5, 1, 9, 5485, 'White Walker', 'killedBy', 'Jon Snow', 'CH_363', 'CH_123'),
 (5, 1, 9, 5485, 'White Walker', 'killedBy', 'Jon Snow', 'CH_364', 'CH_123'),
 (5, 1, 46, 5614, 'Karsi', 'killedBy', 'Wight children', 'CH_129', None),
 (5, 2, 9, 5640, 'Shireen Baratheon', 'killedBy', 'Melisandre', 'CH_312', 'CH_208'),
 (5, 2, 39, 5740, 'Hizdahr zo Loraq', 'killedBy', 'Sons of the Harpy', 'CH_101', None),
 (5, 2, 42, 5759, 'Selyse Baratheon', 'killedBy', 'Selyse Baratheon', 'CH_301', 'CH_301'),
 (5, 3, 3, 5781, 'Gordy', 'killedBy', 'Stannis Baratheon', 'CH_662', 'CH_316'),
 (5, 3, 6, 5784, 'Simpson', 'killedBy', 'Stannis Baratheon', 'CH_663', 'CH_316'),
 (5, 3, 6, 5785, 'Stannis Baratheon', 'killedBy', 'Brienne of Tarth', 'CH_316', 'CH_31'),
 (5, 3, 28, 5844, 'Myranda', 'killedBy', 'Theon Greyjoy', 'CH_228', 'CH_336'),
 (5, 4, 30, 6012, 'Meryn Trant', 'killedBy', 'Arya Stark', 'CH_211', 'CH_15'),
 (5, 4, 33, 6023, "Jaqen H'ghar", 'killedBy', "Jaqen H'ghar", 'CH_115', 'CH_115'),
 (5, 4, 44, 6048, 'Myrcella Baratheon', 'killedBy', 'Ellaria Sand', 'CH_229', 'CH_62'),
 (5, 4, 51, 6056, 'Jon Snow', 'killedBy', 'Olly', 'CH_123', 'CH_249'),
 (5, 5, 4, 6076, 'Bolton Officer', 'killedBy', 'Brienne of Tarth', 'CH_669', 'CH_31'),
 (5, 6, 8, 6213, 'Bolton Soldier', 'killedBy', 'Podrick Payne', 'CH_670', 'CH_258'),
 (5, 6, 38, 6298, 'Areo Hotah', 'killedBy', 'Tyene Sand', 'CH_11', 'CH_348'),
 (5, 6, 38, 6301, 'Maester Caleotte', 'killedBy', 'Tyene Sand', 'CH_671', 'CH_348'),
 (5, 7, 13, 6348, 'Doran Martell', 'killedBy', 'Ellaria Sand', 'CH_52', 'CH_62'),
 (5, 8, 24, 6488, 'Trystane Martell', 'killedBy', 'Obara Sand', 'CH_346', 'CH_244'),
 (5, 8, 44, 6535, "King's Landing Boaster", 'killedBy', 'Gregor Clegane', 'CH_675', 'CH_87'),
 (5, 8, 45, 6538, 'Roose Bolton', 'killedBy', 'Ramsay Snow', 'CH_291', 'CH_269'),
 (5, 8, 47, 6543, 'Walda Bolton', 'killedBy', 'Ramsay Snow', 'CH_356', 'CH_269'),
 (5, 9, 39, 6697, 'Newborn Bolton', 'killedBy', 'Ramsay Snow', 'CH_676', 'CH_269'),
 (5, 9, 47, 6731, 'Balon Greyjoy', 'killedBy', 'Euron Greyjoy', 'CH_17', 'CH_65'),
 (5, 10, 5, 6775, 'Gerold Hightower', 'killedBy', 'Young Ned Stark', 'CH_71', 'CH_386'),
 (5, 10, 24, 6803, 'Arthur Dayne', 'killedBy', 'Howland Reed', 'CH_14', 'CH_105'),
 (5, 10, 24, 6804, 'Shaggydog', 'killedBy', 'Smalljon Umber', 'CH_311', 'CH_314'),
 (5, 10, 26, 6806, 'Alliser Thorne', 'killedBy', 'Jon Snow', 'CH_5', 'CH_123'),
 (5, 10, 30, 6811, 'Othell Yarwyck', 'killedBy', 'Jon Snow', 'CH_254', 'CH_123'),
 (5, 10, 35, 6821, 'Bowen Marsh', 'killedBy', 'Jon Snow', 'CH_27', 'CH_123'),
 (5, 10, 37, 6826, 'Olly', 'killedBy', 'Jon Snow', 'CH_249', 'CH_123'),
 (5, 10, 40, 6839, 'Akho', 'killedBy', 'Daario Naharis', 'CH_4', 'CH_43'),
 (5, 10, 64, 6908, 'Iggo', 'killedBy', 'Daario Naharis', 'CH_685', 'CH_43'),
 (6, 1, 14, 6952, 'Osha', 'killedBy', 'Ramsay Snow', 'CH_253', 'CH_269'),
 (6, 1, 14, 6953, 'Khal Moro', 'killedBy', 'Daenerys Targaryen', 'CH_134', 'CH_44'),
 (6, 1, 25, 6980, 'Dothraki Bloodrider #1', 'killedBy', 'Daenerys Targaryen', 'CH_54', 'CH_44'),
 (6, 1, 25, 6984, 'Dothraki Bloodrider #2', 'killedBy', 'Daenerys Targaryen', 'CH_55', 'CH_44'),
 (6, 1, 26, 6986, 'Khal Forzho', 'killedBy', 'Daenerys Targaryen', 'CH_686', 'CH_44'),
 (6, 1, 27, 6988, 'Khal Brozho', 'killedBy', 'Daenerys Targaryen', 'CH_687', 'CH_44'),
 (6, 2, 17, 7099, 'Khal Rhalko', 'killedBy', 'Daenerys Targaryen', 'CH_135', 'CH_44'),
 (6, 2, 33, 7138, 'Khal Qorro', 'killedBy', 'Daenerys Targaryen', 'CH_688', 'CH_44'),
 (6, 2, 34, 7142, 'Euron Greyjoy', 'killedBy', 'Aeron Greyjoy', 'CH_65', 'CH_2'),
 (6, 2, 34, 7144, 'White Walker', 'killedBy', 'Meera Reed', 'CH_362', 'CH_205'),
 (6, 2, 34, 7144, 'White Walker', 'killedBy', 'Meera Reed', 'CH_363', 'CH_205'),
 (6, 2, 34, 7144, 'White Walker', 'killedBy', 'Meera Reed', 'CH_364', 'CH_205'),
 (6, 2, 39, 7157, 'Summer', 'killedBy', 'Wights', 'CH_326', None),
 (6, 3, 6, 7197, 'Three-Eyed Raven', 'killedBy', 'The Night King', 'CH_339', 'CH_332'),
 (6, 3, 7, 7202, 'Leaf', 'killedBy', 'Wights', 'CH_159', None),
 (6, 3, 32, 7305, 'Hodor', 'killedBy', 'Wights', 'CH_102', None),
 (6, 3, 35, 7315, 'Brother Ray', 'killedBy', 'Lem Lemoncloak', 'CH_33', 'CH_160'),
 (6, 3, 35, 7316, 'Steve', 'killedBy', 'Sandor Clegane', 'CH_714', 'CH_299'),
 (6, 3, 35, 7317, 'Morgan', 'killedBy', 'Sandor Clegane', 'CH_567', 'CH_299'),
 (6, 3, 35, 7318, 'Riddell', 'killedBy', 'Sandor Clegane', 'CH_713', 'CH_299'),
 (6, 4, 18, 7387, 'Gatins', 'killedBy', 'Sandor Clegane', 'CH_69', 'CH_299'),
 (6, 4, 18, 7388, 'Lem Lemoncloak', 'killedBy', 'Sandor Clegane', 'CH_160', 'CH_299'),
 (6, 4, 30, 7420, 'Lady Crane', 'killedBy', 'The Waif', 'CH_151', 'CH_334'),
 (6, 4, 39, 7467, 'The Waif', 'killedBy', 'Arya Stark', 'CH_334', 'CH_15'),
 (6, 4, 39, 7468, 'Razdal mo Eraz', 'killedBy', 'Grey Worm', 'CH_273', 'CH_91'),
 (6, 4, 39, 7469, 'Belicho Paenymion', 'killedBy', 'Grey Worm', 'CH_680', 'CH_91'),
 (6, 4, 39, 7470, 'Rickon Stark', 'killedBy', 'Ramsay Snow', 'CH_285', 'CH_269'),
 (6, 4, 39, 7471, 'Smalljon Umber', 'killedBy', 'Tormund Giantsbane', 'CH_314', 'CH_345'),
 (6, 4, 39, 7472, 'Wun Wun', 'killedBy', 'Ramsay Snow', 'CH_373', 'CH_269'),
 (6, 4, 39, 7473, 'Ramsay Snow', 'killedBy', 'Sansa Stark', 'CH_269', 'CH_300'),
 (6, 5, 28, 7580, 'Grand Maester Pycelle', 'killedBy', 'Frances', 'CH_78', 'CH_679'),
 (6, 5, 59, 7696, 'Lancel Lannister', 'killedBy', 'Cersei Lannister', 'CH_152', 'CH_38'),
 (6, 5, 60, 7697, 'Margaery Tyrell', 'killedBy', 'Cersei Lannister', 'CH_199', 'CH_38'),
 (6, 5, 67, 7712, 'High Sparrow', 'killedBy', 'Cersei Lannister', 'CH_100', 'CH_38'),
 (6, 5, 69, 7718, 'Loras Tyrell', 'killedBy', 'Cersei Lannister', 'CH_174', 'CH_38'),
 (6, 5, 84, 7745, 'Mace Tyrell', 'killedBy', 'Cersei Lannister', 'CH_185', 'CH_38'),
 (6, 7, 46, 8065, 'Kevan Lannister', 'killedBy', 'Cersei Lannister', 'CH_132', 'CH_38'),
 (6, 8, 5, 8079, 'Tommen Baratheon', 'killedBy', 'Tommen Baratheon', 'CH_344', 'CH_344'),
 (6, 8, 6, 8082, 'Lothar Frey', 'killedBy', 'Arya Stark', 'CH_179', 'CH_15'),
 (6, 8, 6, 8083, 'Black Walder Rivers', 'killedBy', 'Arya Stark', 'CH_25', 'CH_15'),
 (6, 8, 7, 8085, 'Walder Frey', 'killedBy', 'Arya Stark', 'CH_357', 'CH_15'),
 (6, 8, 46, 8179, 'Obara Sand', 'killedBy', 'Euron Greyjoy', 'CH_244', 'CH_65'),
 (6, 8, 50, 8190, 'Nymeria Sand', 'killedBy', 'Euron Greyjoy', 'CH_243', 'CH_65'),
 (6, 8, 51, 8192, 'Tyene Sand', 'killedBy', 'Cersei Lannister', 'CH_348', 'CH_38'),
 (6, 9, 12, 8235, 'Olenna Tyrell', 'killedBy', 'Jaime Lannister', 'CH_248', 'CH_113'),
 (6, 9, 12, 8236, 'Randyll Tarly', 'killedBy', 'Daenerys Targaryen', 'CH_270', 'CH_44'),
 (6, 9, 36, 8316, 'Dickon Tarly', 'killedBy', 'Daenerys Targaryen', 'CH_48', 'CH_44'),
 (6, 9, 57, 8366, 'Kevin Eldon', 'killedBy', 'Gendry', 'CH_730', 'CH_70'),
 (6, 9, 63, 8383, 'Laurence Spellman', 'killedBy', 'Gendry', 'CH_731', 'CH_70'),
 (6, 9, 71, 8405, 'White Walker', 'killedBy', 'Jon Snow', 'CH_362', 'CH_123'),
 (6, 9, 71, 8405, 'White Walker', 'killedBy', 'Jon Snow', 'CH_363', 'CH_123'),
 (6, 9, 71, 8405, 'White Walker', 'killedBy', 'Jon Snow', 'CH_364', 'CH_123'),
 (6, 10, 30, 8481, 'Viserion', 'killedBy', 'The Night King', 'CH_354', 'CH_332'),
 (6, 10, 48, 8526, 'Benjen Stark', 'killedBy', 'Wights', 'CH_20', None),
 (6, 10, 49, 8527, 'Harrag', 'killedBy', 'Theon Greyjoy', 'CH_725', 'CH_336'),
 (6, 10, 49, 8528, 'Petyr Baelish', 'killedBy', 'Arya Stark', 'CH_257', 'CH_15'),
 (6, 10, 49, 8529, 'Ned Umber', 'killedBy', 'The Night King', 'CH_230', 'CH_332'),
 (6, 10, 49, 8530, 'Eddison Tollett', 'killedBy', 'Wight', 'CH_60', None),
 (6, 10, 49, 8531, 'Lyanna Mormont', 'killedBy', 'Wun Wun Wight', 'CH_182', 'CH_722'),
 (6, 10, 55, 8540, 'Wun Wun Wight', 'killedBy', 'Lyanna Mormont', 'CH_722', 'CH_182'),
 (6, 10, 75, 8592, 'Beric Dondarrion', 'killedBy', 'Wights', 'CH_21', None),
 (6, 10, 75, 8593, 'Theon Greyjoy', 'killedBy', 'The Night King', 'CH_336', 'CH_332'),
 (6, 10, 76, 8594, 'The Night King', 'killedBy', 'Arya Stark', 'CH_332', 'CH_15'),
 (7, 2, 48, 8882, 'White Walker', 'killedBy', 'Arya Stark', 'CH_362', 'CH_15'),
 (7, 2, 48, 8882, 'White Walker', 'killedBy', 'Arya Stark', 'CH_363', 'CH_15'),
 (7, 2, 48, 8882, 'White Walker', 'killedBy', 'Arya Stark', 'CH_364', 'CH_15'),
 (7, 2, 49, 8885, 'Viserion', 'killedBy', 'Arya Stark', 'CH_354', 'CH_15'),
 (7, 3, 17, 8970, 'Jorah Mormont', 'killedBy', 'Wights', 'CH_125', None),
 (7, 3, 50, 9032, 'Rhaegal', 'killedBy', 'Euron Greyjoy', 'CH_278', 'CH_65'),
 (7, 5, 6, 9273, 'Missandei', 'killedBy', 'Gregor Clegane', 'CH_216', 'CH_87'),
 (7, 5, 6, 9274, 'Lord Varys', 'killedBy', 'Daenerys Targaryen', 'CH_177', 'CH_44'),
 (7, 5, 33, 9338, 'Harry Strickland', 'killedBy', 'Grey Worm', 'CH_96', 'CH_91'),

This is my final result, it includes the number of season, spisode and scene. And the characters and relationship in each scenes. Since some characters like 'White Walker' have seceral id, so it may not be distinct for each scene.

<u>Python Code</u>

$$ \alpha^2 $$

### Data Access Abstraction

- A common API and abstraction for manipulating different database types and schema simplifies the development of web applications and other applications. There are many abstractions.

| <img src="./Lecture_4_ER_SQL_Relational_GoT_9.jpg"> |
| :---: |
| __Data Access Objects__ |

- The second programming tasks is to implement our own abstraction. This is RDBDataTable, which implements an abstraction we will use in subsequent homework assignments, and which we will use to enable our web application.


- You can find the implementation template in the ```src``` directory of the project template.


- For HW 1, Part C, you can copy your implementation code into this notebook and test again the cloud databases.


- __I strongly suggest that you develop and test in PyCharm, and then copy your code into the notebook. The cells below just show you where to place your code. You should copy your code over from PyCharm.__

#### Implementation

- ```BaseDataTable``` defines the common abstraction we will use. You do not need to do anything to this class.

In [16]:
# Import package to enable defining abstract classes in Python.
# Do not worry about understanding abstract base classes. This is just a class that defines
# some methods that subclasses must implement.
from abc import ABC, abstractmethod


class DataTableException(Exception):
    """
    A simple class that maps underlying implementation exceptions to generic exceptions.
    """

    invalid_method = 1001

    # General
    def __init__(self, code, message):
        self.code = code
        self.message = message

    def __str__(self):
        result = (
            type(self), {"code": self.code, "message": self.message}
        )
        result = str(result)
        return result


class BaseDataTable(ABC):
    """
    The implementation classes (XXXDataTable) for CSV database, relational, etc. will extend the
    base class and implement the abstract methods.
    """

    def __init__(self, entity_type_name, connect_info, key_columns=None, context=None):
        """

        :param entity_type_name: Name of the logcal entity type. This maps to various abstractions in
            underlying stores, e.g. file names, RDB tables, Neo4j Labels, ...
        :param connect_info: Dictionary of parameters necessary to connect to the data. See examples in subclasses.
        :param key_columns: List, in order, of the columns (fields) that comprise the primary key.
            A primary key is a set of columns whose values are unique and uniquely identify a row. For Appearances,
            the columns are ['playerID', 'teamID', 'yearID']
        :param contex: Holds context and environment information.
        """
        self._table_name = entity_type_name
        self._connect_info = connect_info
        self._key_columns = key_columns
        self._context = context

    @abstractmethod
    def find_by_primary_key(self, key_fields, field_list=None, context=None):
        """

        :param key_fields: The values for the key_columns, in order, to use to find a record. For example,
            for Appearances this could be ['willite01', 'BOS', '1960']
        :param field_list: A subset of the fields of the record to return. The CSV file or RDB table may have many
            additional columns, but the caller only requests this subset.
        :return: None, or a dictionary containing the columns/values for the row.
        """
        pass

    @abstractmethod
    def find_by_template(self, template, field_list=None, limit=None, offset=None, order_by=None, context=None):
        """

        :param template: A dictionary of the form { "field1" : value1, "field2": value2, ...}. The function will return
            a derived table containing the rows that match the template.
        :param field_list: A list of requested fields of the form, ['fielda', 'fieldb', ...]
        :param limit: Do not worry about this for now.
        :param offset: Do not worry about this for now.
        :param order_by: Do not worry about this for now.
        :return: A derived table containing the computed rows.
        """
        pass

    @abstractmethod
    def insert(self, new_entity, context=None):
        """

        :param new_record: A dictionary representing a row to add to the set of records. Raises an exception if this
            creates a duplicate primary key.
        :return: None
        """
        pass

    @abstractmethod
    def delete_by_template(self, template, context=None):
        """

        Deletes all records that match the template.

        :param template: A template.
        :return: A count of the rows deleted.
        """
        pass

    @abstractmethod
    def delete_by_key(self, key_fields, Context=None):
        """

        Delete record with corresponding key.

        :param key_fields: List containing the values for the key columns
        :return: A count of the rows deleted.
        """
        pass

    @abstractmethod
    def update_by_template(self, template, new_values, context=None):
        """

        :param template: A template that defines which matching rows to update.
        :param new_values: A dictionary containing fields and the values to set for the corresponding fields
            in the records. This returns an error if the update would create a duplicate primary key. NO ROWS are
            update on this error.
        :return: The number of rows updates.
        """
        pass

    @abstractmethod
    def update_by_key(self, key_fields, new_values, context=None):
        """

        :param key_fields: List of values for primary key fields
        :param new_values: A dictionary containing fields and the values to set for the corresponding fields
            in the records. This returns an error if the update would create a duplicate primary key. NO ROWS are
            update on this error.
        :return: The number of rows updates.
        """
        pass

    @abstractmethod
    def query(self, query_statement, args, context=None):
        """
        Passed through/executes a raw query in the native implementation language of the backend.
        :param query_statement: Query statement as a string.
        :param args: Args to insert into query if it is a template
        :param context:
        :return: A JSON object containing the result of the operation.
        """
        pass

    @abstractmethod
    def load(self, rows=None):
        """
        Loads data into the data table.
        :param rows:
        :return: Number of rows loaded.
        """

    @abstractmethod
    def save(self, context):
        """
        Writes any cached data to a backing store.
        :param context:
        :return:
        """

__RDBDataTable__


- You only need to implement the following methods:
    - ```__init__```
    - ```__str__```
    - ```find_by_template``` You only need to implement the parameters
        - ```template```
        - ```field_list```
    - ```find_by_primary_key``` You only need to implement the parameters
        - ```key_fields```
        - ```field_list```


- The logical behavior of the ```find_by_template``` API is the following:
    - If you create an ```RDBDataTable``` instance for a SQL table ```GoTSolutionClean.scenes_characters,```
    - The call<br>
```
    characters_tbl.find_by_template(
            template={
                'seasonNum': 1,
                'episodeNum': 2
                },
            field_list = ['seasonNum', 'episodeNum', 'sceneNo', 'character_id']
            )
```
    - Is equivalent to
```
    select seasonNum, episodeNum, sceneNo, character_id
        from GoTSolutionClean.scenes_characters
        where
            seasonNum=1 and episodeNum=1
```
    - And returns the same dictionary.

- The logical behavior of the ```find_by_primary_key``` API is the following:
    - If you create an ```RDBDataTable``` instance for a SQL table ```GoTSolutionClean.episodes,```
    - The primary key columns are ```seasonNum, episodeNum.```
    - The invocation would be ```find_by_primary_key([1,3],field_list=['seasonNum','episodeNum','title'])```
    - This would get converted into
```
select seasonNum, episodeNum, title
        from W4111GoTSolutionClean.episodes
        where
            seasonNum=1 and episodeNum=1
```
    - Your class implementation MUST run a database query to determine the primary key columns and their order to form the ```where``` clause.
    - The result is a single dictionary containing the query result.
    
    
- We will provide tests.

In [8]:
from src.data_tables.BaseDataTable import BaseDataTable

import pandas as pd
import pymysql

import logging

logger = logging.getLogger()


class RDBDataTable(BaseDataTable):
    """
    RDBDataTable is relation DB implementation of the BaseDataTable.
    """

    # Default connection information in case the code does not pass an object
    # specific connection on object creation.
    _default_connect_info = pymysql.connect(
        host="columbia8013.cqgsme1nmjms.us-east-1.rds.amazonaws.com",
        user="gotuser",
        password="gotusergotuser",
        db="W4111GoTSolutionClean",
        cursorclass=pymysql.cursors.DictCursor)

    _default_cnx = None

    @classmethod
    def _get_default_cnx(cls):

        if RDBDataTable._default_cnx is None:
            # Create a connection to use inside this object. In general, this is not the right approach.
            # There would be a connection pool shared across many classes and applications.
            cls._default_cnx = pymysql.connect(
                host="columbia8013.cqgsme1nmjms.us-east-1.rds.amazonaws.com",
                user="gotuser",
                password="gotusergotuser",
                db="W4111GoTSolutionClean",
                cursorclass=pymysql.cursors.DictCursor)

            return cls._default_cnx

    def __init__(self, table_name, key_columns=None, connect_info=None):
        """

        :param table_name: The name of the RDB table.
        :param connect_info: Dictionary of parameters necessary to connect to the data.
        :param key_columns: List, in order, of the columns (fields) that comprise the primary key.
            This is for compatibility with other types of data table. Any value other than None is an error.
        """

        # If there is not explicit connect information, use the defaults.
        
        ####### Your Code Goes Here #########
        schema_name=table_name.split(sep='.')[0]
        if connect_info is None:
            connect_info=pymysql.connect(
        host="columbia8013.cqgsme1nmjms.us-east-1.rds.amazonaws.com",
        user="gotuser",
        password="gotusergotuser",
        db="W4111GoTSolutionClean",
        cursorclass=pymysql.cursors.DictCursor)
        
        #if key_columns is None:
        #    sql = "select * from characters where characterName=%s"
        #    cur = connect_info.cursor()
        #    res = cur.execute(sql, (c_name))
        #    res = cur.fetchall()
        #    return res
        sql=f"show columns from {table_name}"
        cur = connect_info.cursor()
        res = cur.execute(sql)
        res = cur.fetchall()
        key_columns=[i['Field'] for i in res if i['Key']=='PRI']
            
            
        self._table_name = table_name
        self._connect_info = connect_info
        self._key_columns = key_columns
        
        ####### Your Code Goes Here #########


    def __str__(self):
        """

        :return: String representation of the table's metadata.
        """
        ####### Your Code Goes Here #########
        from pandas.io.json import json_normalize
        result = f"table_name: {self._table_name}"#, "key_columns": self._key_columns        
        result = str(result)
        sql=f"show columns from {self._table_name}"
        cur = self._connect_info.cursor()
        res = cur.execute(sql)
        res = cur.fetchall()
        key_columns=[i['Field'] for i in res if i['Key']=='PRI']
        result=result+f'\nKey Columns:\n{key_columns}'+f'\nColumns:\n{res}'
        sql2=f"select * from {self._table_name}"
        res2 = cur.execute(sql2)
        res2 = cur.fetchall()
        result2=json_normalize(res2).head()
        result+='\n\n'+'Some rows: \n\n'+str(result2)
        return result
        
        ####### Your Code Goes Here #########


    @classmethod
    def _run_q(cls, q, args=None, fields=None, fetch=True, cnx=None, cursor=None, commit=True):
        """

        :param q: An SQL query string that may have %s slots for argument insertion. The string
            may also have {} after select for columns to choose.
        :param args: A tuple of values to insert in the %s slots.
        :param fetch: If true, return the result.
        :param cnx: A database connection. May be None
        :param cncursor: Do not worry about this for now.
        :param commit: Do not worry about this for now. This is more wizard stuff.
        :return: A result set or None.
        """

        r = None

        cursor_created = False

        if cnx is None:
            cnx = cls._get_default_cnx()

        try:
            # Use the connection in the object if no connection provided.


            # Convert the list of columns into the form "col1, col2, ..." for following SELECT.
            if fields:
                q = q.format(",".join(fields))

            if cursor is None:
                cursor = cnx.cursor()  # Just ignore this for now.
                cursor_created = True

            # If debugging is turned on, will print the query sent to the database.
            #self.debug_message("Query = ", cursor.mogrify(q, args))

            cursor.execute(q, args)  # Execute the query.

            # Technically, INSERT, UPDATE and DELETE do not return results.
            # Sometimes the connector libraries return the number of created/deleted rows.
            if fetch:
                r = cursor.fetchall()  # Return all elements of the result.
            else:
                r = None

            if commit:                  # Do not worry about this for now.
                cnx.commit()

            if cursor_created:
                cursor.close()

        except Exception as e:
            print("Exception e = ", e)
            if commit:
                cnx.rollback()
            if cursor_created:
                cursor.close()

        return r

    def _run_insert(self, table_name, column_list, values_list, cnx=None, commit=True):
        """

        :param table_name: Name of the table to insert data. Probably should just get from the object data.
        :param column_list: List of columns for insert.
        :param values_list: List of column values.
        :param cnx: Ignore this for now.
        :param commit: Ignore this for now.
        :return:
        """
        try:
            q = "insert into " + table_name + " "

            # If the column list is not None, form the (col1, col2, ...) part of the statement.
            if column_list is not None:
                q += "(" + ",".join(column_list) + ") "

            # We will use query parameters. For a term of the form values(%s, %s, ...) with one slot for
            # each value to insert.
            values = ["%s"] * len(values_list)

            # Form the values(%s, %s, ...) part of the statement.
            values = " ( " + ",".join(values) + ") "
            values = "values" + values

            # Put all together.
            q += values

            self._run_q(q, args=values_list, fields=None, fetch=False, cnx=cnx, commit=commit)

        except Exception as e:
            print("Got exception = ", e)
            raise e

    @classmethod
    def get_folders(cls,dbname=None):
        #cur = pymysql.connect(
        #host="columbia8013.cqgsme1nmjms.us-east-1.rds.amazonaws.com",
        #user="gotuser",
        #password="gotusergotuser",
        #db="W4111GoTSolutionClean",
        #cursorclass=pymysql.cursors.DictCursor)
        cur=cls._default_connect_info
        cur=cur.cursor()
        if dbname is None:
            res = cur.execute('show schemas')
            res = cur.fetchall()
            print ('dbs= \n',[n for x in res for m,n in x.items()])
        else:                       
            res = cur.execute('show tables from '+dbname)
            res = cur.fetchall()           
            print ('tbls= \n',[n for x in res for m,n in x.items()])
        pass

    def find_by_primary_key(self, key_fields, field_list=None, context=None):
        """

        :param key_fields: The values for the key_columns, in order, to use to find a record.
        :param field_list: A subset of the fields of the record to return.
        :return: None, or a dictionary containing the request fields for the record identified
            by the key.
        """
        
        
        ####### Your Code Goes Here #########
        try:
            if field_list is not None:
                p = ','.join(field_list) 
            q = "select "+ p + ' from '+self._table_name+" where "
            num=len(self._key_columns)
            for i in range(num):
                if i!=(num-1):
                    q+=f'{self._key_columns[i]}={key_fields[i]} and '
                else:
                    q+=f'{self._key_columns[i]}={key_fields[i]}'
            cur = self._connect_info.cursor()
            res = cur.execute(q)
            res = cur.fetchall()
            return res

        except Exception as e:
            print("Got exception = ", e)
            raise e        
        
        ####### Your Code Goes Here #########

    def _template_to_where_clause(self, t):
        """
        Convert a query template into a WHERE clause.
        :param t: Query template.
        :return: (WHERE clause, arg values for %s in clause)
        """
        w_clause=None
        args = None
        
        ####### Your Code Goes Here #########
        
        
        
        
        
        ####### Your Code Goes Here #########

        return w_clause, args
    
    def get_key_columns(self):
        sql=f"show columns from {self._table_name}"
        cur = self._connect_info.cursor()
        res = cur.execute(sql)
        res = cur.fetchall()
        key_columns=[i['Field'] for i in res if i['Key']=='PRI']
        return key_columns

    def find_by_template(self, template, field_list=None, limit=None, offset=None, order_by=None, commit=True):
        """

        :param template: A dictionary of the form { "field1" : value1, "field2": value2, ...}
        :param field_list: A list of request fields of the form, ['fielda', 'fieldb', ...]
        :param limit: Do not worry about this for now.
        :param offset: Do not worry about this for now.
        :param order_by: Do not worry about this for now.
        :return: A list containing dictionaries. A dictionary is in the list representing each record
            that matches the template. The dictionary only contains the requested fields.
        """
        ####### Your Code Goes Here #########
        try:
            if field_list is not None:
                p = ','.join(field_list) 
            q = "select "+ p + ' from '+self._table_name+" where "
            m=[]
            for i,j in template.items():
                m.append(f'{i}={j}')
            q=q+' and '.join(m)
            cur = self._connect_info.cursor()
            res = cur.execute(q)
            res = cur.fetchall()
            return res

        except Exception as e:
            print("Got exception = ", e)
            raise e   
        
        ####### Your Code Goes Here #########



    def insert(self, new_record):
        """

        :param new_record: A dictionary representing a row to add to the set of records.
        :return: None
        """
        pass

    def delete_by_template(self, template):
        """

        Deletes all records that match the template.

        :param template: A template.
        :return: A count of the rows deleted.
        """
        pass

    def delete_by_key(self, key_fields):
        """

        Delete record with corresponding key.

        :param key_fields: List containing the values for the key columns
        :return: A count of the rows deleted.
        """
        pass

    def update_by_template(self, template, new_values):
        """

        :param template: A template that defines which matching rows to update.
        :param new_values: A dictionary containing fields and the values to set for the corresponding fields
            in the records. This returns an error if the update would create a duplicate primary key. NO ROWS are
            update on this error.
        :return: The number of rows updates.
        """
        pass

    def update_by_key(self, key_fields, new_values):
        """

        :param key_fields: List of values for primary key fields
        :param new_values: A dictionary containing fields and the values to set for the corresponding fields
            in the records. This returns an error if the update would create a duplicate primary key. NO ROWS are
            update on this error.
        :return: The number of rows updates.
        """
        pass

    def load(self):
        pass

    def save(self):
        pass

    def query(self, query_statement, args, context=None):
        pass

__Tests__

- We will provide some tests.

In [9]:
from src.data_tables.RDBDataTable import RDBDataTable
import json

def t1():

    print("\n************** t1 **************\n")

    tbl = RDBDataTable("W4111GoTSolutionClean.episodes")
    print("Table = ", tbl)
    print("\n")
    #tbl = RDBDataTable("W4111GoTSolution.episodes")
    #print("Table = ", tbl)

    print("\n************** t1 **************\n")


def t2():

    print("\n************** t2 **************\n")

    tbl = RDBDataTable("W4111GoTSolutionClean.episodes")

    res = tbl.find_by_template(
        {"seasonNum": 1},
        field_list=['seasonNum', 'episodeNum', 'episodeTitle']
    )

    print("Answer = ")
    print(json.dumps(res, indent=2, default=str))

    print("\n************** t2 **************\n")


def t3():


    print("\n************** t3 **************\n")

    tbl = RDBDataTable("W4111GoTSolutionClean.scenes")

    res = tbl.find_by_primary_key([3,1, 11],
        field_list=['seasonNum', 'episodeNum', 'sceneNo', "location", "subLocation"]
    )

    print("Answer = \n")
    print(json.dumps(res, indent=2, default=str))


    print("\n************** t3 **************\n")


def t4():

    print("\n************** t4 **************\n")
    dbs = RDBDataTable.get_folders()
    print("dbs = ", json.dumps(dbs, indent=2))
    print("\n")

    tbls = RDBDataTable.get_folders(dbname="W4111GoTSolutionClean")
    print("tbls = ", json.dumps(tbls, indent=2))
    print("\n************** t4 **************\n")


def t5():

    print("\n************** t5 **************\n")

    tbl = RDBDataTable("W4111GoTSolutionClean.scenes")

    k = tbl.get_key_columns()
    print("Key columns = ", k)

    print("\n************** t5 **************\n")



t1()
t2()
t3()
t4()
t5()

************** t1 **************

Table =  table_name: W4111GoTSolutionClean.episodes
Key Columns:
['id']
Columns:
[{'Field': 'id', 'Type': 'int(11)', 'Null': 'NO', 'Key': 'PRI', 'Default': None, 'Extra': ''}, {'Field': 'seasonNum', 'Type': 'int(11)', 'Null': 'NO', 'Key': 'MUL', 'Default': None, 'Extra': ''}, {'Field': 'episodeNum', 'Type': 'int(11)', 'Null': 'NO', 'Key': '', 'Default': None, 'Extra': ''}, {'Field': 'episodeTitle', 'Type': 'varchar(64)', 'Null': 'NO', 'Key': '', 'Default': None, 'Extra': ''}, {'Field': 'episodeLink', 'Type': 'varchar(64)', 'Null': 'NO', 'Key': '', 'Default': None, 'Extra': ''}, {'Field': 'episodeAirDate', 'Type': 'date', 'Null': 'NO', 'Key': '', 'Default': None, 'Extra': ''}, {'Field': 'episodeDescription', 'Type': 'varchar(256)', 'Null': 'NO', 'Key': '', 'Default': None, 'Extra': ''}]

Some rows:

   id  seasonNum  episodeNum                           episodeTitle  \
0   0          1           1                       Winter Is Coming
1   1          1           2                          The Kingsroad
2   2          1           3                              Lord Snow
3   3          1           4  Cripples, Bastards, and Broken Things
4   4          1           5                  The Wolf and the Lion

         episodeLink episodeAirDate  \
0  /title/tt1480055/     2011-04-17
1  /title/tt1668746/     2011-04-24
2  /title/tt1829962/     2011-05-01
3  /title/tt1829963/     2011-05-08
4  /title/tt1829964/     2011-05-15

                                  episodeDescription
0  Jon Arryn, the Hand of the King, is dead. King...
1  While Bran recovers from his fall, Ned takes o...
2  Lord Stark and his daughters arrive at King's ...
3  Eddard investigates Jon Arryn's murder. Jon be...
4  Catelyn has captured Tyrion and plans to bring...



************** t1 **************


************** t2 **************

Answer =
[
  {
    "seasonNum": 1,
    "episodeNum": 1,
    "episodeTitle": "Winter Is Coming"
  },
  {
    "seasonNum": 1,
    "episodeNum": 2,
    "episodeTitle": "The Kingsroad"
  },
  {
    "seasonNum": 1,
    "episodeNum": 3,
    "episodeTitle": "Lord Snow"
  },
  {
    "seasonNum": 1,
    "episodeNum": 4,
    "episodeTitle": "Cripples, Bastards, and Broken Things"
  },
  {
    "seasonNum": 1,
    "episodeNum": 5,
    "episodeTitle": "The Wolf and the Lion"
  },
  {
    "seasonNum": 1,
    "episodeNum": 6,
    "episodeTitle": "A Golden Crown"
  },
  {
    "seasonNum": 1,
    "episodeNum": 7,
    "episodeTitle": "You Win or You Die"
  },
  {
    "seasonNum": 1,
    "episodeNum": 8,
    "episodeTitle": "The Pointy End"
  },
  {
    "seasonNum": 1,
    "episodeNum": 9,
    "episodeTitle": "Baelor"
  },
  {
    "seasonNum": 1,
    "episodeNum": 10,
    "episodeTitle": "Fire and Blood"
  }
]

************** t2 **************


************** t3 **************

Answer =

[
  {
    "seasonNum": 3,
    "episodeNum": 1,
    "sceneNo": 11,
    "location": "North of the Wall",
    "subLocation": "Frostfang Mountains"
  }
]

************** t3 **************


************** t4 **************

dbs=
 ['W4111GoTSolutionClean', 'information_schema']
dbs =  null


tbls=
 ['actors_episodes', 'character_interactions', 'character_relationships', 'character_relationships_old', 'characters', 'characters_actors', 'characters_locations', 'episodes', 'groups', 'groups_old', 'locations', 'locations_old', 'locations_sublocations', 'scenes', 'scenes_characters', 'sublocations']
tbls =  null

************** t4 **************


************** t5 **************

Key columns =  ['seasonNum', 'episodeNum', 'sceneNo']

************** t5 **************

All five tests about HW1C has passed